name: build and deploy using docker

on: push

permissions:
  contents: read

jobs:
  build_and_deploy_using_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy to main
        if: contains(github.ref, 'main')
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}
            sudo docker rm -f hometender-api
            sudo docker run --name hometender-api -d -p 8080:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKER_REPO }}
            sudo docker image prune -f

      - name: Deploy to dev
        if: contains(github.ref, 'dev')
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: GITHUB_SHA
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}:${{ steps.meta.outputs.tags }}
            sudo docker rm -f hometender-api
            sudo docker run --name hometender-api -d -p 8080:8080 -e TZ=Asia/Seoul ${{ secrets.DOCKER_REPO }}:${{ steps.meta.outputs.tags }}
            sudo docker image prune -f

      - name: Slack Notify
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: group-dev
          SLACK_COLOR: '#FF2D00'
          SLACK_USERNAME: 'Github Action'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_TITLE: Build Failure - ${{ github.event.pull_request.title }}
          SLACK_MESSAGE: PR Url - ${{ github.event.pull_request.url }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
